version: "3"

services:

  redbeansoup:
    image: denoland/deno:alpine
    depends_on:
      - db
    #restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
    - ./:/app # redbeansoup source code
    - /deno-dir # persist cached dependancies
    working_dir: /app
    command: deno run --import-map import_map.json --allow-all mod.ts
    networks:
      - redbeansoup-network-dev

  db:
    image: mysql:8-oracle
    command: --log-error-verbosity=3
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: redbeansoup
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'redbeansoup-bot' #replace with your own password
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - redbeansoup-network-dev


networks:
  redbeansoup-network-dev:

volumes:
  my-db:
