version: "3"

services:
  redbeansoup:
    image: denoland/deno:alpine
    depends_on:
      - db
    #restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
    - ./:/app # redbeansoup source code
    - /deno-dir # persist cached dependancies in a proper volume
    working_dir: /app
    command: deno run --import-map import_map.json --allow-all mod.ts
